version: '3.8'

services:
  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python main.py
    restart: unless-stopped 